apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: progress-check-gitops
  description: This is GitOps manifest for progress-check   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: progress-check
    janus-idp.io/tekton: progress-check 
    backstage.io/kubernetes-id: progress-check 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:progress-check
