apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: progress-check
  janus-idp.io/tekton: progress-check
  backstage.io/kubernetes-id: progress-check
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: progress-check
resources:
- deployment.yaml
- route.yaml
- service.yaml
